### ISSUE TITLE
 expected dtype Byte but got dtype Bool

### ISSUE THREAD

**Issue by Fee532** [JKBox/YOLOv3-quadrangle#12]
Traceback (most recent call last):
  File "/home/fee/PycharmProjects/YOLOv3-quadrangle/train.py", line 173, in <module>
    main(opt)
  File "/home/fee/PycharmProjects/YOLOv3-quadrangle/train.py", line 109, in main
    loss = model(imgs.to(device), targets, requestPrecision=True)
  File "/home/fee/.conda/envs/envhrank/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fee/PycharmProjects/YOLOv3-quadrangle/models.py", line 235, in forward
    x, *losses = module[0](x, targets, requestPrecision)
  File "/home/fee/.conda/envs/envhrank/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fee/PycharmProjects/YOLOv3-quadrangle/models.py", line 149, in forward
    requestPrecision)
  File "/home/fee/PycharmProjects/YOLOv3-quadrangle/utils/utils.py", line 257, in build_targets
    TP[b, i] = (pconf > 0.5) & (iou_pred > 0.5) & (pcls == tc.cpu())
RuntimeError: expected dtype Byte but got dtype Bool

Process finished with exit code 1
environment: pytorch 1.4.0 python3.6

**Comment by Fee532** [comment]
solved method: use pytorch 1.1.0
