### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by ashuezy** [JKBox/YOLOv3-quadrangle#6]
```
Namespace(batch_size=4, cfg='cfg/yolov3.cfg', data_config_path='cfg/ICDAR2015.data', epochs=100, img_size=640000, resume=False)
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    main(opt)
  File "train.py", line 38, in main
    model = Darknet(opt.cfg, opt.img_size)
  File "/opt/github/YOLOv3-quadrangle/models.py", line 213, in __init__
    self.hyperparams, self.module_list = create_modules(self.module_defs)
  File "/opt/github/YOLOv3-quadrangle/models.py", line 56, in create_modules
    yolo_layer = YOLOLayer(anchors, num_classes, img_height, anchor_idxs)
  File "/opt/github/YOLOv3-quadrangle/models.py", line 92, in __init__
    self.grid_x = torch.arange(nG).repeat(nG, 1).view([1, 1, nG, nG]).float()
RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

```

**Comment by xiyufeng2** [comment]
loss = model(imgs.to(device), targets, requestPrecision=True)，
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float32)
it seems like targets can't be float32.

**Comment by vineeth357** [comment]
where and format of training dataaet??
